const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.DragnDrop,
		C3.Plugins.Mouse,
		C3.Behaviors.scrollto,
		C3.Behaviors.DragnDrop.Cnds.OnDrop,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.SetLayoutScale,
		C3.Plugins.System.Acts.SetVar
	];
};
self.C3_JsPropNameTable = [
	{ZiehenUndLoslassen: 0},
	{Sprite: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{Sprite7: 0},
	{JosephWilliams6PartsCompressed: 0},
	{Sprite8: 0},
	{Sprite9: 0},
	{Sprite10: 0},
	{Sprite11: 0},
	{Sprite12: 0},
	{Sprite13: 0},
	{Sprite14: 0},
	{gameTitle: 0},
	{dressupGame: 0},
	{blankForEinrasten: 0},
	{blankForEinrasten2: 0},
	{Maus: 0},
	{Sprite15: 0},
	{Sprite16: 0},
	{Sprite17: 0},
	{ScrolleZu: 0},
	{Sprite18KameraAnker: 0},
	{Sprite18: 0},
	{Sprite2: 0},
	{ringstext: 0},
	{sunglassestext: 0},
	{ZoomStatus: 0},
	{Klick_X: 0},
	{Klick_Y: 0}
];

self.InstanceType = {
	Sprite: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	JosephWilliams6PartsCompressed: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	gameTitle: class extends self.ISpriteInstance {},
	dressupGame: class extends self.ISpriteInstance {},
	blankForEinrasten: class extends self.ISpriteInstance {},
	blankForEinrasten2: class extends self.ISpriteInstance {},
	Maus: class extends self.IInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	Sprite18KameraAnker: class extends self.ISpriteInstance {},
	Sprite18: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	ringstext: class extends self.ISpriteInstance {},
	sunglassestext: class extends self.ISpriteInstance {}
}